(() => {
  const { IconInfo, IconChevronDown, IconCheck, IconSearch, IconClock, IconExternal, IconGift, IconCheckCircle } = NKI;
  const { FunnelChip, RewardChip, FriendAvatar } = NKS;
  function Progress({ data }) {
    return /* @__PURE__ */ React.createElement("section", { className: "pg-card pg-rise", "data-screen-label": "Your progress" }, /* @__PURE__ */ React.createElement("div", { className: "pg-card__head" }, /* @__PURE__ */ React.createElement("span", { className: "pg-eyebrow" }, "Your progress"), /* @__PURE__ */ React.createElement("h2", { className: "pg-card__title" }, "How your invites are doing")), /* @__PURE__ */ React.createElement("div", { className: "pg-kpis" }, data.kpis.map((k, i) => /* @__PURE__ */ React.createElement("div", { key: i, className: "pg-kpi" + (k.reward ? " pg-kpi--reward" : "") }, /* @__PURE__ */ React.createElement("div", { className: "pg-kpi__num" }, k.num), /* @__PURE__ */ React.createElement("div", { className: "pg-kpi__lbl" }, k.label)))), /* @__PURE__ */ React.createElement("div", { className: "pg-stepper" }, data.steps.map((s, i) => /* @__PURE__ */ React.createElement(React.Fragment, { key: i }, i > 0 && /* @__PURE__ */ React.createElement("div", { className: "pg-step-bar" + (i <= 2 ? " is-on" : "") }), /* @__PURE__ */ React.createElement("div", { className: "pg-step" + (i < 3 ? " is-on" : "") + (s.final ? " is-final" : "") }, /* @__PURE__ */ React.createElement("div", { className: "pg-step__dot" }, s.n), /* @__PURE__ */ React.createElement("div", { className: "pg-step__lbl" }, s.label))))), /* @__PURE__ */ React.createElement("p", { className: "pg-note" }, /* @__PURE__ */ React.createElement(IconInfo, { size: 16 }), /* @__PURE__ */ React.createElement("span", null, "The first steps (shared \u2192 clicked) appear once sharing tracking is added; statuses come from the backend.")));
  }
  function HowItWorks() {
    const dico = (name) => "assets/icons/design/" + name + ".svg";
    const steps = [
      { ic: "letter", h: "Share your link", body: /* @__PURE__ */ React.createElement(React.Fragment, null, "On WhatsApp or a group chat \u2014 wherever your friends already are.") },
      { ic: "rocket", h: "Your friend joins", body: /* @__PURE__ */ React.createElement(React.Fragment, null, "They sign up via your link and get a ", /* @__PURE__ */ React.createElement("b", null, "welcome discount"), " after their trial.") },
      { ic: "gift", h: "You earn free lessons", body: /* @__PURE__ */ React.createElement(React.Fragment, null, "Trial \u2192 ", /* @__PURE__ */ React.createElement("b", null, "1 free lesson"), ". Subscribe \u2192 ", /* @__PURE__ */ React.createElement("b", null, "1 free month"), " (8 lessons), no limits.") }
    ];
    return /* @__PURE__ */ React.createElement("section", { className: "pg-card pg-rise", "data-screen-label": "How it works" }, /* @__PURE__ */ React.createElement("div", { className: "pg-card__head" }, /* @__PURE__ */ React.createElement("span", { className: "pg-eyebrow" }, "How it works"), /* @__PURE__ */ React.createElement("h2", { className: "pg-card__title" }, "Three steps to free lessons")), /* @__PURE__ */ React.createElement("div", { className: "pg-how" }, steps.map((s, i) => /* @__PURE__ */ React.createElement("div", { key: i, className: "pg-how__step" }, /* @__PURE__ */ React.createElement("div", { className: "pg-how__chip" }, /* @__PURE__ */ React.createElement("img", { src: dico(s.ic), alt: "" }), /* @__PURE__ */ React.createElement("span", { className: "pg-how__n" }, i + 1)), /* @__PURE__ */ React.createElement("h4", null, s.h), /* @__PURE__ */ React.createElement("p", null, s.body)))));
  }
  function FriendRows({ friends }) {
    return /* @__PURE__ */ React.createElement("div", null, friends.map((f) => /* @__PURE__ */ React.createElement("div", { key: f.id, className: "pg-friend-row" }, /* @__PURE__ */ React.createElement(FriendAvatar, { initial: f.initial, id: f.id }), /* @__PURE__ */ React.createElement("div", { className: "pg-friend-meta" }, /* @__PURE__ */ React.createElement("div", { className: "pg-friend-name" }, "Friend #", f.id), /* @__PURE__ */ React.createElement("div", { className: "pg-friend-date" }, "Invited ", f.date)), /* @__PURE__ */ React.createElement("div", { className: "pg-friend-chips" }, /* @__PURE__ */ React.createElement(FunnelChip, { funnel: f.funnel }), /* @__PURE__ */ React.createElement(RewardChip, { reward: f.reward })))));
  }
  function FriendCards({ friends }) {
    return /* @__PURE__ */ React.createElement("div", { className: "pg-friend-grid" }, friends.map((f) => /* @__PURE__ */ React.createElement("div", { key: f.id, className: "pg-friend-card" }, /* @__PURE__ */ React.createElement("div", { className: "pg-friend-card__top" }, /* @__PURE__ */ React.createElement(FriendAvatar, { initial: f.initial, id: f.id }), /* @__PURE__ */ React.createElement("div", { className: "pg-friend-meta" }, /* @__PURE__ */ React.createElement("div", { className: "pg-friend-name" }, "Friend #", f.id), /* @__PURE__ */ React.createElement("div", { className: "pg-friend-date" }, "Invited ", f.date))), /* @__PURE__ */ React.createElement("div", { className: "pg-friend-card__chips" }, /* @__PURE__ */ React.createElement(FunnelChip, { funnel: f.funnel }), /* @__PURE__ */ React.createElement(RewardChip, { reward: f.reward })))));
  }
  function Friends({ data, variant }) {
    const [open, setOpen] = React.useState(false);
    const total = data.friends.length;
    const shown = open ? data.friends : data.friends.slice(0, 4);
    return /* @__PURE__ */ React.createElement("section", { className: "pg-card pg-rise", "data-screen-label": "Invited friends" }, /* @__PURE__ */ React.createElement("div", { className: "pg-card__head" }, /* @__PURE__ */ React.createElement("span", { className: "pg-eyebrow" }, "Your invited friends"), /* @__PURE__ */ React.createElement("h2", { className: "pg-card__title" }, "Who you've invited"), /* @__PURE__ */ React.createElement("p", { className: "pg-card__sub" }, "Names are masked for privacy. Statuses update as your friends progress.")), variant === "cards" ? /* @__PURE__ */ React.createElement(FriendCards, { friends: shown }) : /* @__PURE__ */ React.createElement(FriendRows, { friends: shown }), total > 4 && /* @__PURE__ */ React.createElement("button", { className: "pg-showall" + (open ? " is-open" : ""), onClick: () => setOpen(!open) }, open ? "Show fewer" : `Show all ${total} invited friends`, /* @__PURE__ */ React.createElement(IconChevronDown, { size: 16 })));
  }
  function Rewards({ data }) {
    return /* @__PURE__ */ React.createElement("section", { className: "pg-card pg-rise", "data-screen-label": "Your rewards" }, /* @__PURE__ */ React.createElement("div", { className: "pg-card__head" }, /* @__PURE__ */ React.createElement("span", { className: "pg-eyebrow" }, "Your rewards"), /* @__PURE__ */ React.createElement("h2", { className: "pg-card__title" }, "What you've earned")), /* @__PURE__ */ React.createElement("div", { className: "pg-reward-summary" }, /* @__PURE__ */ React.createElement("div", { className: "pg-reward-summary__ic" }, /* @__PURE__ */ React.createElement("img", { src: "assets/icons/design/medal.svg", alt: "" })), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("div", { className: "pg-reward-summary__t" }, "Earned so far"), /* @__PURE__ */ React.createElement("div", { className: "pg-reward-summary__v" }, /* @__PURE__ */ React.createElement("span", { className: "lemon" }, "1 free month"), " + ", /* @__PURE__ */ React.createElement("span", { className: "lemon" }, "2 free lessons")))), /* @__PURE__ */ React.createElement("div", null, data.ledger.map((r, i) => {
      const granted = r.kind === "granted";
      return /* @__PURE__ */ React.createElement("div", { key: i, className: "pg-ledger-row" }, /* @__PURE__ */ React.createElement("div", { className: "pg-ledger-ic " + (granted ? "pg-ledger-ic--granted" : "pg-ledger-ic--review") }, granted ? /* @__PURE__ */ React.createElement(IconGift, { size: 22 }) : /* @__PURE__ */ React.createElement(IconSearch, { size: 22 })), /* @__PURE__ */ React.createElement("div", { className: "pg-ledger-meta" }, /* @__PURE__ */ React.createElement("div", { className: "pg-ledger-amt" }, r.amount, r.note ? /* @__PURE__ */ React.createElement("span", { style: { color: "var(--nk-text-muted)", fontWeight: 400 } }, " \xB7 ", r.note) : null), /* @__PURE__ */ React.createElement("div", { className: "pg-ledger-sub" }, r.who, " \xB7 ", r.date)), /* @__PURE__ */ React.createElement("span", { className: "pg-chip " + (granted ? "pg-chip--granted" : "pg-chip--review") }, granted ? /* @__PURE__ */ React.createElement(IconCheck, { size: 15 }) : /* @__PURE__ */ React.createElement(IconClock, { size: 15 }), granted ? "Granted" : "Under review"));
    })));
  }
  function FriendBanner() {
    return /* @__PURE__ */ React.createElement("section", { className: "pg-banner-friend pg-rise", "data-screen-label": "What your friend gets" }, /* @__PURE__ */ React.createElement("div", { className: "pg-banner-friend__ic" }, /* @__PURE__ */ React.createElement("img", { src: "assets/icons/design/gift.svg", alt: "" })), /* @__PURE__ */ React.createElement("div", null, /* @__PURE__ */ React.createElement("h4", null, "What your friend gets"), /* @__PURE__ */ React.createElement("p", null, "A special welcome discount after their first trial lesson, so the link you send is a real gift, not just an ad.")));
  }
  function Promo({ onLearnMore }) {
    return /* @__PURE__ */ React.createElement("section", { className: "pg-promo pg-rise", "data-screen-label": "Promo" }, /* @__PURE__ */ React.createElement("div", { className: "pg-promo__ic" }, /* @__PURE__ */ React.createElement("img", { src: "assets/icons/design/joystick.svg", alt: "" })), /* @__PURE__ */ React.createElement("div", { className: "pg-promo__body" }, /* @__PURE__ */ React.createElement("div", { className: "pg-promo__title" }, /* @__PURE__ */ React.createElement("h4", null, "Win a PlayStation 5 by inviting friends"), /* @__PURE__ */ React.createElement("span", { className: "pg-promo__badge" }, "Ends 30 Jun")), /* @__PURE__ */ React.createElement("p", { className: "pg-promo__sub" }, "Most invites by 30 June wins \u2014 a seasonal bonus on top of the always-on free-lessons program.")), /* @__PURE__ */ React.createElement("a", { className: "pg-promo__link", href: "#", onClick: (e) => {
      e.preventDefault();
      onLearnMore && onLearnMore();
    } }, "Learn more ", /* @__PURE__ */ React.createElement(IconExternal, { size: 15 })));
  }
  function FaqItem({ item, isOpen, onToggle }) {
    const ref = React.useRef(null);
    return /* @__PURE__ */ React.createElement("div", { className: "pg-faq-item" + (isOpen ? " is-open" : "") }, /* @__PURE__ */ React.createElement("button", { className: "pg-faq-q", onClick: onToggle, "aria-expanded": isOpen }, /* @__PURE__ */ React.createElement("span", null, item.q), /* @__PURE__ */ React.createElement("span", { className: "pg-faq-q__ic" }, /* @__PURE__ */ React.createElement(IconChevronDown, { size: 16 }))), /* @__PURE__ */ React.createElement("div", { className: "pg-faq-a", ref, style: { maxHeight: isOpen ? ref.current ? ref.current.scrollHeight : 400 : 0 } }, /* @__PURE__ */ React.createElement("div", { className: "pg-faq-a__in" }, item.a)));
  }
  function Faq({ data }) {
    const [open, setOpen] = React.useState(0);
    return /* @__PURE__ */ React.createElement("section", { className: "pg-card pg-rise", "data-screen-label": "FAQ" }, /* @__PURE__ */ React.createElement("div", { className: "pg-card__head" }, /* @__PURE__ */ React.createElement("span", { className: "pg-eyebrow" }, "Good to know"), /* @__PURE__ */ React.createElement("h2", { className: "pg-card__title" }, "Frequently asked questions")), /* @__PURE__ */ React.createElement("div", null, data.faq.map((item, i) => /* @__PURE__ */ React.createElement(FaqItem, { key: i, item, isOpen: open === i, onToggle: () => setOpen(open === i ? -1 : i) }))));
  }
  window.NKS = Object.assign(window.NKS || {}, {
    Progress,
    HowItWorks,
    Friends,
    Rewards,
    FriendBanner,
    Promo,
    Faq
  });
})();
